### ISSUE TITLE
firstText and lastText not working

### ISSUE THREAD

**Issue by benrnorman** [hashtagerrors/pagination#1]
Hi,

Thank you for this plugin.

The firstText and lastText options don't work as intended. They are ignored and remain as  "First" and "Last", unless prevText or nextText are also provided in which case they take these variables.

I think this is due to a bug on lines 11 and 13 of this file: 
https://github.com/hashtagerrors/pagination/blob/master/src/templates/_render/_paginate.twig

It currently reads:
```
{% set firstText = options.prevText ?? 'First' %}

{% set lastText = options.nextText ?? 'Last' %}
```

I think it is meant to read:
```
{% set firstText = options.firstText ?? 'First' %}

{% set lastText = options.lastText ?? 'Last' %}
```

**Comment by hashtagerrors** [comment]
Fixed in v1.0.1.
