### ISSUE TITLE
Duplication of query params

### ISSUE THREAD

**Issue by epartipilo** [hashtagerrors/pagination#2]
```twig
craft.pagination.render(
  pageInfo,
  'numeric',
  {
    includePrevNext: true
  }
)
```

If I have this path:
`http://localhost/finishes?search=hello`
and the I click for example _next page_ link I get this:
`http://localhost/finishes/p2?search=hello?search=hello`

**Comment by hashtagerrors** [comment]
Fixed in v1.0.2
